import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation",
    price: 199.99,
    currency: "USD",
    image: "https://picsum.photos/400/300?random=1",
    featured: true,
    category: "accessories",
  },
  {
    id: "2",
    name: "Smartphone",
    description: "Latest model with advanced camera system",
    price: 999.99,
    currency: "USD",
    image: "https://picsum.photos/400/300?random=2",
    featured: true,
    category: "devices",
  },
  {
    id: "3",
    name: "Laptop",
    description: "Powerful laptop for work and gaming",
    price: 1499.99,
    currency: "USD",
    image: "https://picsum.photos/400/300?random=3",
    featured: true,
    category: "devices",
  },
  {
    id: "4",
    name: "Smartwatch",
    description: "Track your fitness and stay connected",
    price: 299.99,
    currency: "USD",
    image: "https://picsum.photos/400/300?random=4",
    category: "devices",
  },
  {
    id: "5",
    name: "Wireless Earbuds",
    description: "Compact and comfortable wireless earbuds",
    price: 149.99,
    currency: "USD",
    image: "https://picsum.photos/400/300?random=5",
    category: "accessories",
  },
  {
    id: "6",
    name: "Tablet",
    description: "Versatile tablet for work and entertainment",
    price: 599.99,
    currency: "USD",
    image: "https://picsum.photos/400/300?random=6",
    category: "devices",
  },
];
